"""add foreign key

Revision ID: b078bf96285c
Revises: 81258829b981
Create Date: 2025-05-27 12:06:50.498037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b078bf96285c"
down_revision: Union[str, None] = "81258829b981"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("customer_id", "customers", ["customer_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint("customer_id", type_="foreignkey")
        batch_op.drop_column("customer_id")

    # ### end Alembic commands ###
